# Generated by Django 6.0.3 on 2026-03-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='game',
            field=models.CharField(choices=[('free_fire', 'Free Fire'), ('fc_mobile', 'FC Mobile')], default='fc_mobile', max_length=20),
        ),
    ]
