# Generated by Django 6.0.3 on 2026-03-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_code',
            field=models.CharField(blank=True, choices=[('fc_points_80', 'FC Mobile: 80 поинтс'), ('fc_points_40', 'FC Mobile: 40 поинтс'), ('fc_coins', 'FC Mobile: монеты'), ('ff_100', 'Free Fire: 100 алмазов'), ('ff_310', 'Free Fire: 310 алмазов'), ('ff_520', 'Free Fire: 520 алмазов'), ('ff_1060', 'Free Fire: 1060 алмазов'), ('ff_weekly', 'Free Fire: недельный ваучер'), ('ff_lite', 'Free Fire: ваучер лайт')], max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('points', 'Поинтс'), ('coins', 'Монеты'), ('diamonds', 'Алмазы'), ('vouchers', 'Ваучеры')], max_length=20),
        ),
    ]
