# Generated by Django 6.0.3 on 2026-03-30 12:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_product_code_alter_order_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price_rub',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_tjs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
