# Generated by Django 6.0.3 on 2026-03-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_order_price_rub_alter_order_price_tjs'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailauthcode',
            name='mode',
            field=models.CharField(choices=[('login', 'Login'), ('signup', 'Signup')], default='login', max_length=20),
        ),
        migrations.AddField(
            model_name='emailauthcode',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
