# Generated by Django 6.0.3 on 2026-03-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_emailauthcode_mode_emailauthcode_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('waiting', 'Ожидает оплату'), ('review', 'На проверке'), ('approved', 'Оплата подтверждена')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('points', 'Points'), ('coins', 'Coins'), ('diamonds', 'Алмазы'), ('vouchers', 'Ваучеры')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_code',
            field=models.CharField(blank=True, choices=[('fc_points_80', 'FC Mobile: 80 Points'), ('fc_points_40', 'FC Mobile: 40 Points'), ('fc_coins', 'FC Mobile: Coins'), ('ff_100', 'Free Fire: 100 алмазов'), ('ff_310', 'Free Fire: 310 алмазов'), ('ff_520', 'Free Fire: 520 алмазов'), ('ff_1060', 'Free Fire: 1060 алмазов'), ('ff_weekly', 'Free Fire: Недельный ваучер'), ('ff_lite', 'Free Fire: Ваучер лайт')], max_length=40),
        ),
    ]
