# Generated by Django 6.0.3 on 2026-03-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_order_paid_at_order_payment_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_password',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
